In [1]:
import pandas as pd
data=pd.read_csv(r"C:\Users\vrish\OneDrive\Documents\AI\Project\readmission dataset.csv")

In [2]:
data.isnull()

,patient_id,age,gender,weight_kg,height_cm,bmi,num_previous_admissions,chronic_conditions,medications_count,last_hemoglobin,...,length_of_stay,procedures_count,smoking_status,alcohol_use,physical_activity,insurance_type,followup_compliance,social_support,mental_health_issue,readmission_risk
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
data.sum()

patient_id                 d8fd1a56-a5d8-499b-917c-f9ac8d369f9b2e9b4349-6...
age                                                                   444596
gender                     MaleFemaleFemaleFemaleMaleMaleMaleFemaleFemale...
weight_kg                                                             792469
height_cm                                                            1693602
bmi                                                                 285431.6
num_previous_admissions                                                44966
chronic_conditions         Heart DiseaseDiabetesHeart DiseaseHypertension...
medications_count                                                      44332
last_hemoglobin                                                     139929.7
last_glucose                                                       1354722.1
last_creatinine                                                     12441.46
admission_type             EmergencyElectiveUrgentElectiveEmergencyElecti...
length_of_stay                                                        150503
procedures_count                                                       20101
smoking_status             CurrentNeverNeverFormerFormerFormerCurrentForm...
alcohol_use                ModerateHighModerateHighModerateModerateModera...
physical_activity          MediumMediumLowHighHighMediumLowHighLowHighLow...
insurance_type             PrivatePrivatePublicPrivateUninsuredUninsuredU...
followup_compliance        PoorGoodGoodGoodPoorPoorGoodGoodGoodPoorPoorPo...
social_support             WeakWeakWeakWeakWeakWeakStrongStrongWeakStrong...
mental_health_issue        YesYesNoNoNoNoNoNoNoYesYesNoNoNoNoNoNoYesNoYes...
readmission_risk           MediumHighLowHighMediumHighLowHighMediumLowLow...
dtype: object

In [4]:
data.describe()

,age,weight_kg,height_cm,bmi,num_previous_admissions,medications_count,last_hemoglobin,last_glucose,last_creatinine,length_of_stay,procedures_count
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.00000,9999.000000,9999.000000
mean,44.464046,79.254825,169.377138,28.546015,4.497050,4.433643,13.994369,135.485759,1.24427,15.051805,2.010301
std,25.987773,23.168501,17.347572,10.450597,2.869846,2.874026,2.297621,37.488959,0.43686,8.360688,1.414848
min,0.000000,40.000000,140.000000,10.100000,0.000000,0.000000,10.000000,70.000000,0.50000,1.000000,0.000000
25%,22.000000,59.000000,154.000000,20.400000,2.000000,2.000000,12.000000,102.800000,0.86000,8.000000,1.000000
50%,45.000000,79.000000,169.000000,27.400000,5.000000,4.000000,14.000000,135.500000,1.24000,15.000000,2.000000
75%,67.000000,99.000000,184.500000,35.100000,7.000000,7.000000,16.000000,168.400000,1.62000,22.000000,3.000000
max,89.000000,119.000000,199.000000,60.200000,9.000000,9.000000,18.000000,200.000000,2.00000,29.000000,4.000000

In [5]:
data.dropna()

,patient_id,age,gender,weight_kg,height_cm,bmi,num_previous_admissions,chronic_conditions,medications_count,last_hemoglobin,...,length_of_stay,procedures_count,smoking_status,alcohol_use,physical_activity,insurance_type,followup_compliance,social_support,mental_health_issue,readmission_risk
0,d8fd1a56-a5d8-499b-917c-f9ac8d369f9b,18,Male,57,157,23.1,8,Heart Disease,8,16.2,...,7,0,Current,Moderate,Medium,Private,Poor,Weak,Yes,Medium
1,2e9b4349-69e5-494f-b806-947ec5b5bb7c,23,Female,117,150,52.0,6,Diabetes,6,13.1,...,21,2,Never,High,Medium,Private,Good,Weak,Yes,High
2,6f279c22-3b20-4328-9dac-466de7c47a51,80,Female,61,141,30.7,5,Heart Disease,8,15.4,...,2,0,Never,Moderate,Low,Public,Good,Weak,No,Low
4,e7903dbe-839e-4ea6-a6d0-83438a981a9b,14,Male,67,179,20.9,6,Heart Disease,0,14.7,...,3,0,Former,High,High,Uninsured,Poor,Weak,No,Medium
5,41bf6d3e-6ec8-4519-b2a5-b916532f73b8,74,Male,79,151,34.6,8,Heart Disease,2,10.6,...,22,4,Former,Moderate,Medium,Uninsured,Poor,Weak,No,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,53934a95-897f-4ce9-9415-02af84875476,60,Female,41,152,17.7,8,Heart Disease,5,18.0,...,27,4,Never,Moderate,Low,Public,Good,Weak,Yes,Low
9994,37b15f13-ab5d-4881-a12f-2a3a10a76c37,59,Male,58,163,21.8,7,Heart Disease,1,11.4,...,7,2,Never,Moderate,High,Public,Poor,Strong,No,Medium
9996,77912d1d-d45f-4681-ab06-1d3853a25eed,3,Male,111,160,43.4,2,Diabetes,2,13.1,...,7,4,Former,Moderate,Medium,Private,Poor,Strong,No,Medium
9997,30aea26e-a9df-4e0c-9e21-91318ee643b0,68,Male,97,190,26.9,3,COPD,3,12.4,...,16,4,Former,High,Low,Public,Good,Strong,No,Low
9998,a2ff97be-6e2e-4565-b1cf-2370870b664b,20,Female,55,150,24.4,5,Hypertension,5,11.5,...,25,2,Former,Moderate,High,Public,Good,Weak,No,High

In [6]:
data.columns

Index(['patient_id', 'age', 'gender', 'weight_kg', 'height_cm', 'bmi',
       'num_previous_admissions', 'chronic_conditions', 'medications_count',
       'last_hemoglobin', 'last_glucose', 'last_creatinine', 'admission_type',
       'length_of_stay', 'procedures_count', 'smoking_status', 'alcohol_use',
       'physical_activity', 'insurance_type', 'followup_compliance',
       'social_support', 'mental_health_issue', 'readmission_risk'],
      dtype='str')

In [7]:
import pandas as pd
import numpy as np

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error,r2_score

In [9]:
X=data.drop(columns=['patient_id'])

In [10]:
Y=['gender','smoking_status','alcohol_use','admission_type','insurance_type','social_support','mental_health_issue']

In [11]:
data=pd.get_dummies(data,columns=Y,drop_first=True)

In [12]:
X=data.drop('readmission_risk',axis=1)
Y=data['readmission_risk']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2, random_state=42)

In [14]:
model= RandomForestClassifier(n_estimators=100, random_state=42)

In [15]:
X=pd.get_dummies(X,drop_first=True)

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [17]:
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [18]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [19]:
Y_pred=model.predict(X_test)

In [22]:
print(f"accuracy_score : {accuracy_score(Y_test,Y_pred):%}")
print("\n---Detailed Report---")
print(classification_report(Y_test,Y_pred))

accuracy_score : 32.650000%

---Detailed Report---
              precision    recall  f1-score   support

        High       0.33      0.31      0.32       688
         Low       0.35      0.33      0.34       673
      Medium       0.30      0.34      0.32       639

    accuracy                           0.33      2000
   macro avg       0.33      0.33      0.33      2000
weighted avg       0.33      0.33      0.33      2000

In [23]:
new_patient_data={'age':[45],
                  'gender':['Male'],
                  'weight_kg':[80.5],
                    'height_cm': [175],
                    'bmi': [26.3],
                    'num_previous_admission':[1],
                      'chronic_conditions':[2],
                      'medications_count':[3],
                      'last_hemoglobin': [13.5],
                      'last_glucose':[110],
                      'last_creatinine':[1.1],
                      'admission_type':['Emergency'],
                      'length_of stay':[4],
                      'procedures_count':[1],
                      'smoking_status':['Never'],
                      'alcohol_use':['Occasional'],
                      'physical_activity':[3],
                      'insurance_type':['Private'],
                      'followup_compliance':[1],
                      'social_support':['High'],
                      'mental_health_issue':['No']
                      }

In [24]:
new_patient_data=pd.DataFrame(new_patient_data)

In [25]:
new_patient_data=pd.get_dummies(new_patient_data)

In [26]:
new_patient_data=new_patient_data.reindex(columns=X_train.columns,fill_value=0)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [29]:
scaler.fit(X)

StandardScaler()

In [30]:
new_patient_data=scaler.transform(new_patient_data)

In [31]:
prediction=model.predict(new_patient_data)

C:\Users\vrish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [32]:
probability=model.predict_proba(new_patient_data)

C:\Users\vrish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [33]:
print(f"prediction risk level:{prediction[0]}")

prediction risk level:High

In [34]:
confidence=float(max(probability[0]))
print(f"model confidence :{confidence*100:2f}%")

model confidence :38.000000%

In [35]:
pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: tzdata in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\vrish\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\vrish\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [36]:
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
sns.set_theme(style="whitegrid")

In [38]:
plt.figure(figsize=(10,6))

In [39]:
order=['Low','Medium','High']

In [40]:
new_patient_data=pd.DataFrame(data,columns=['risk_level'])

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [ ]:
pip install --upgrade pip

In [53]:
from tensorflow import keras
from tensorflow.keras import layers 
from keras_tuner import RandomSearch

ModuleNotFoundError: No module named 'tensorflow.python'

In [51]:
pip install tensorflow import keras

Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow
  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement import (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\vrish\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for import